Repository abap-observability-tools/abap-metrics-provider, pull requests merged in 2021-03, with the labels that each got.

#182 Regenerate maintenance view
  src/zamp_customizing/zamp_config_mp.fugr.lzamp_config_mpf00.abap
  src/zamp_customizing/zamp_config_mp.fugr.lzamp_config_mpi00.abap
  src/zamp_customizing/zamp_config_mp.fugr.lzamp_config_mpt00.abap
  src/zamp_customizing/zamp_config_mp.fugr.lzamp_config_mptop.abap
  src/zamp_customizing/zamp_config_mp.fugr.saplzamp_config_mp.abap
  src/zamp_customizing/zamp_config_mp.fugr.viewframe_zampv_config_pro.abap
  src/zamp_customizing/zamp_config_mp.fugr.viewframe_zampv_config_sce.abap
  src/zamp_customizing/zamp_config_mp.fugr.viewproc_zampv_config_pro.abap
  src/zamp_customizing/zamp_config_mp.fugr.viewproc_zampv_config_sce.abap
  src/zamp_customizing/zamp_config_mp.fugr.xml
  src/zamp_customizing/zamp_configc.tobj.xml
  src/zamp_customizing/zampv_config_pro.view.xml
  src/zamp_customizing/zampv_config_sce.view.xml
Labels: bug, customizing, patch

#183 Use ABAP escape function to escape JSON
  src/zamp_converter/zcl_amp_conv_http_json.clas.abap
Labels: chore, patch

#188 Switch metric value to int4
  src/zamp_metric_value.dtel.xml
Labels: chore, minor

#193 abaplint npm package removed
  package-lock.json
  package.json
Labels: misc, patch

#195 Add prometheus config example
  local-tests/prometheus/prometheus.yml
Labels: misc, patch

#197 Update local tests readme
  local-tests/README.md
Labels: documentation, misc, patch
